name: Basic CI

on:
  push:
    branchs: ['main']

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v4
      - name: Install CURL
        run: |
          sudo apt update
          sudo apt install curl
      - name: Run Composer
        run: composer install
      - name: Run server
        run: sudo php artisan server
      - name: Curl request
        run: curl localhost
